// Generated by CoffeeScript 1.7.1
(function() {
  window.SimpleSlider = (function() {
    function SimpleSlider(options) {
      this.pushcontent = options.$pushcontent;
      this.pushheader = options.$pushheader;
      this.leftbar = options.$leftbar;
      this.rightbar = options.$rightbar;
      this.state = 'center';
    }

    SimpleSlider.prototype.openLeft = function() {
      this.nobar(this.rightbar);
      if (this.state === 'left') {
        this.closeRight();
      }
      this.pushcontent.addClass('movedRight-content');
      this.pushheader.addClass('movedRight-header');
      this.leftbar.removeClass('none');
      return this.state = 'right';
    };

    SimpleSlider.prototype.openRight = function() {
      this.nobar(this.leftbar);
      if (this.state === 'right') {
        this.closeLeft();
      }
      this.pushcontent.addClass('movedLeft-content');
      this.pushheader.addClass('movedLeft-header');
      this.rightbar.removeClass('none');
      return this.state = 'left';
    };

    SimpleSlider.prototype.close = function() {
      if (this.state === 'left') {
        this.nobar(this.rightbar);
      }
      if (this.state === 'right') {
        this.nobar(this.leftbar);
      }
      this.pushcontent.removeClass('movedRight-content');
      this.pushcontent.removeClass('movedLeft-content');
      this.pushheader.removeClass('movedRight-header');
      this.pushheader.removeClass('movedLeft-header');
      return this.state = 'center';
    };

    SimpleSlider.prototype.closeLeft = function() {
      this.pushcontent.removeClass('movedRight-content');
      return this.pushheader.removeClass('movedRight-header');
    };

    SimpleSlider.prototype.closeRight = function() {
      this.pushcontent.removeClass('movedLeft-content');
      return this.pushheader.removeClass('movedLeft-header');
    };

    SimpleSlider.prototype.nobar = function(position) {
      this.pushcontent.off('transitionend');
      return this.pushcontent.on('transitionend', (function(_this) {
        return function() {
          return position.addClass('none');
        };
      })(this));
    };

    SimpleSlider.prototype.pusherState = function() {
      return this.state;
    };

    return SimpleSlider;

  })();

}).call(this);
